[build]
  command = "npm run build"
  publish = "dist"
  functions = "netlify"

[[redirects]]
  from = "/api/google-reviews"
  to = "/.netlify/functions/google-reviews"
  status = 200
  force = true

[[redirects]]
  from = "/api/place-details"
  to = "/.netlify/functions/place-details"
  status = 200
  force = true

[[redirects]]
  from = "/api/places"
  to = "/.netlify/functions/places"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200