[build]
  command = "npm run build"
  publish = "dist"
  functions = "netlify/functions"

# Redirecionamentos para as funções (recomendado)
[[redirects]]
  from = "/api/place-details"
  to = "/.netlify/functions/place-details"
  status = 200
  force = true

[[redirects]]
  from = "/api/places"
  to = "/.netlify/functions/places"
  status = 200
  force = true

[[redirects]]
  from = "/api/google-reviews"
  to = "/.netlify/functions/google-reviews"
  status = 200
  force = true

# Catch-all para a aplicação de página única (SPA)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200