[build]
  command = "npm run build"
  publish = "dist"
  functions = "netlify/functions"

[build.environment]
  GOOGLE_PLACES_API_KEY = "your-api-key-here"

[[redirects]]
  from = "/api/google-reviews"
  to = "/.netlify/functions/google-reviews"
  status = 200

[[redirects]]
  from = "/api/place-details"
  to = "/.netlify/functions/place-details"
  status = 200

[[redirects]]
  from = "/api/places"
  to = "/.netlify/functions/places"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200